feat: add items and users
KazariaFenix/java-shareit pull request #1
Opened 2023-10-04 15:48 UTC by KazariaFenix

2023-10-05 13:53 UTC, mikita95 requested changes
Все сделано отлично. Оставил лишь несколько замечаний

2023-10-05 13:53 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    Item addItem(ItemDto itemDto, long userId);
Репозиторий должен оперировать только сущностями модели данных, он ничего не должен знать про dto

2023-10-05 13:53 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +                throw new IllegalArgumentException();
Лучше пписать сообщение, так понятнее потом при разборе ошибок

2023-10-05 13:53 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +        for (User user : users.values()) {
Для эффективности, чтобы не обходить всех пользовелей, можно хранить email адреса в отдельном множестве (такой индекс своеобразный)

2023-10-05 13:53 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    public Item addItem(ItemDto itemDto, long userId) {
Сервис должен возвращать и принимать только dto, и использовать внутрии мапперы для преобразование одного в другое

2023-10-05 14:32 UTC, KazariaFenix commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    public Item addItem(ItemDto itemDto, long userId) {
Исправлено

2023-10-05 14:32 UTC, KazariaFenix commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    Item addItem(ItemDto itemDto, long userId);
Исправлено

2023-10-05 14:32 UTC, KazariaFenix commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +                throw new IllegalArgumentException();
Написано

2023-10-06 09:26 UTC, mikita95 approved these changes
Все отлично. Можно мержить пул-реквест

2023-10-06 09:31 UTC, merged