feat: add bookings
KazariaFenix/java-shareit pull request #2
Opened 2023-10-25 16:42 UTC by KazariaFenix

2023-10-27 14:00 UTC, mikita95 requested changes
Все сделано отлично. Оставил лишь несколько замечаний

2023-10-27 14:00 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        for (Item item : itemsOwner) {
Так неэффективно выполнять, так как размер коллекции может быть большим и количество запросов в базу тогда будет тоже большим. Стоит запросить все одним или двумя запросами

2023-10-27 14:00 UTC, mikita95 commented on src/main/resources/schema.sql
> +   owner_id BIGINT REFERENCES users ON DELETE CASCADE,
Можно добавить индекс по этой колонке, чтобы запрос выполнялся быстрее

2023-10-27 17:31 UTC, KazariaFenix commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        for (Item item : itemsOwner) {
Исправлено

2023-10-27 17:31 UTC, KazariaFenix commented on src/main/resources/schema.sql
> +   owner_id BIGINT REFERENCES users ON DELETE CASCADE,
Добавлено 3 индекса

2023-10-29 11:54 UTC, KazariaFenix commented
feat: add booking and database

2023-10-29 11:54 UTC, merged